packages:
  - packages/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.2.0
    eslint: ^9.25.1
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
  testing:
    vitest: ^3.1.2
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
