name: Label Sync

on:
  push:
    branches: [main, master]
    paths:
      - .github/labels.json
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const labels = JSON.parse(fs.readFileSync('.github/labels.json', 'utf8'));

            // Get existing labels
            const { data: existingLabels } = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Create or update labels
            for (const label of labels) {
              const existingLabel = existingLabels.find(l => l.name === label.name);

              if (existingLabel) {
                // Update existing label if needed
                if (existingLabel.color !== label.color || existingLabel.description !== label.description) {
                  await github.rest.issues.updateLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description,
                  });
                  console.log(`Updated label: ${label.name}`);
                }
              } else {
                // Create new label
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description,
                });
                console.log(`Created label: ${label.name}`);
              }
            }
